#!/usr/bin/env bash
#===============================================================================
# Textos en Español
#===============================================================================
# Menú principal
MSG_MENU_MAIN_TITLE="${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
MSG_MENU_REPO_SECTION="📦 GESTIÓN DE REPOSITORIOS:"
MSG_MENU_CREATE_NEW="Crear nuevo repositorio desde cero"
MSG_MENU_INIT_EXISTING="Inicializar repositorio en proyecto existente"
MSG_MENU_PUSH_CHANGES="Subir cambios a GitHub (auto-descripción)"
MSG_MENU_CLONE_REPO="Clonar repositorio existente"
MSG_MENU_VIEW_STATUS="Ver estado del repositorio actual"
MSG_MENU_VERSION_SECTION="🌿 CONTROL DE VERSIÓN:"
MSG_MENU_MANAGE_BRANCHES="Configurar ramas (branch)"
MSG_MENU_MANAGE_TAGS="Gestionar tags/releases"
MSG_MENU_VIEW_HISTORY="Ver historial de commits"
MSG_MENU_ADVANCED_SECTION="⚙️  CONFIGURACIÓN AVANZADA:"
MSG_MENU_SETUP_PAGES="Configurar GitHub Pages"
MSG_MENU_SETUP_ACTIONS="Configurar GitHub Actions (CI/CD)"
MSG_MENU_SETUP_GITIGNORE="Configurar .gitignore personalizado"
MSG_MENU_GENERATE_DOCS="Generar documentación automática"
MSG_MENU_UTILITIES_SECTION="🗑️  UTILIDADES:"
MSG_MENU_REMOVE_LOCAL="Eliminar repositorio localmente"
MSG_MENU_EXIT="Salir"
# Mensajes comunes
MSG_SELECT_OPTION="➤ Seleccione una opción:"
MSG_INVALID_OPTION="❌ Opción inválida. Por favor, intente nuevamente."
MSG_PRESS_ENTER="📌 Presione Enter para continuar..."
MSG_GOODBYE="👋 ¡Hasta luego! Gracias por usar GitHub Repository Manager."
MSG_CANCEL="Cancelar"
MSG_YES="s"
MSG_NO="n"
MSG_YES_CAPS="S"
MSG_NO_CAPS="N"
# Cambio de idioma
MSG_CHANGE_LANGUAGE="🌐 Seleccione el idioma / Select language:"
MSG_LANG_CHANGED="✅ Idioma cambiado correctamente / Language changed successfully"
# Autenticación SSH
MSG_SSH_CHECK="🔐 Verificando configuración SSH..."
MSG_SSH_OK="✅ Conexión SSH funcionando correctamente"
MSG_SSH_FAIL="❌ No se detectó configuración SSH válida"
MSG_SSH_HELP="💡 Configura SSH ejecutando: ssh-keygen -t ed25519 -C \"tu@email.com\""
MSG_SSH_ADD_KEY="📌 Luego agrega la clave a GitHub: https://github.com/settings/ssh/new"
MSG_TOKEN_FALLBACK="🔑 Usando token como alternativa..."
MSG_TOKEN_PROMPT="📝 Ingresa tu GitHub Personal Access Token (classic o fine-grained):"
MSG_TOKEN_SAVED="✅ Token guardado en variable de entorno GITHUB_TOKEN"
MSG_AUTH_SUCCESS="✅ Autenticación configurada correctamente"
# Módulo 1 - Crear repositorio
MSG_CREATE_REPO_TITLE="${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
MSG_CREATE_REPO_HEADER="🚀 CREAR NUEVO REPOSITORIO"
MSG_REPO_NAME="📝 Nombre del repositorio:"
MSG_REPO_DESC="📄 Descripción (opcional):"
MSG_REPO_PRIVATE="🔒 ¿Repositorio privado? (s/n):"
MSG_REPO_CREATED="✅ Repositorio creado exitosamente"
MSG_REPO_EXISTS="❌ El repositorio ya existe"
MSG_REPO_CREATE_FAIL="❌ Error al crear el repositorio"
MSG_REPO_URL="🔗 URL del repositorio:"
MSG_REPO_INIT_LOCAL="📦 Inicializando repositorio local..."
MSG_REPO_ADD_REMOTE="🌐 Agregando remote origin..."
MSG_REPO_PUSH_FIRST="📤 Realizando primer push..."
# Módulo 2 - Inicializar en proyecto existente
MSG_INIT_REPO_TITLE="${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
MSG_INIT_REPO_HEADER="📁 INICIALIZAR REPOSITORIO EN PROYECTO EXISTENTE"
MSG_INIT_REPO_PATH="📂 Ruta del proyecto (actual: $(pwd)):"
MSG_INIT_GIT="🔧 Inicializando repositorio Git..."
MSG_INIT_FIRST_COMMIT="💾 Realizando primer commit..."
MSG_INIT_SUCCESS="✅ Repositorio inicializado exitosamente"
MSG_NOT_GIT_REPO="⚠️  Este directorio no es un repositorio Git"
MSG_REPO_ALREADY_INIT="ℹ️  El repositorio ya está inicializado"
# Mensajes de validación
MSG_VALIDATE_NAME="❌ El nombre del repositorio no puede estar vacío"
MSG_VALIDATE_NAME_INVALID="❌ Nombre inválido. Use solo letras, números, guiones y guiones bajos"
MSG_VALIDATE_YES_NO="❌ Por favor responda 's' (sí) o 'n' (no)"
