#!/usr/bin/env bash
#===============================================================================
# Textos en Español (Actualizado con módulos 3, 5, 11)
#===============================================================================
# Menú principal
MSG_MENU_MAIN_TITLE="${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
MSG_MENU_REPO_SECTION="📦 GESTIÓN DE REPOSITORIOS:"
MSG_MENU_CREATE_NEW="Crear nuevo repositorio desde cero"
MSG_MENU_INIT_EXISTING="Inicializar repositorio en proyecto existente"
MSG_MENU_PUSH_CHANGES="Subir cambios a GitHub (auto-descripción)"
MSG_MENU_CLONE_REPO="Clonar repositorio existente"
MSG_MENU_VIEW_STATUS="Ver estado del repositorio actual"
MSG_MENU_VERSION_SECTION="🌿 CONTROL DE VERSIÓN:"
MSG_MENU_MANAGE_BRANCHES="Configurar ramas (branch)"
MSG_MENU_MANAGE_TAGS="Gestionar tags/releases"
MSG_MENU_VIEW_HISTORY="Ver historial de commits"
MSG_MENU_ADVANCED_SECTION="⚙️  CONFIGURACIÓN AVANZADA:"
MSG_MENU_SETUP_PAGES="Configurar GitHub Pages"
MSG_MENU_SETUP_ACTIONS="Configurar GitHub Actions (CI/CD)"
MSG_MENU_SETUP_GITIGNORE="Configurar .gitignore personalizado"
MSG_MENU_GENERATE_DOCS="Generar documentación automática"
MSG_MENU_UTILITIES_SECTION="🗑️  UTILIDADES:"
MSG_MENU_REMOVE_LOCAL="Eliminar repositorio localmente"
MSG_MENU_EXIT="Salir"
# Mensajes comunes
MSG_SELECT_OPTION="➤ Seleccione una opción:"
MSG_INVALID_OPTION="❌ Opción inválida. Por favor, intente nuevamente."
MSG_PRESS_ENTER="📌 Presione Enter para continuar..."
MSG_GOODBYE="👋 ¡Hasta luego! Gracias por usar GitHub Repository Manager."
MSG_CANCEL="Cancelar"
MSG_YES="s"
MSG_NO="n"
MSG_YES_CAPS="S"
MSG_NO_CAPS="N"
# Cambio de idioma
MSG_CHANGE_LANGUAGE="🌐 Seleccione el idioma / Select language:"
MSG_LANG_CHANGED="✅ Idioma cambiado correctamente / Language changed successfully"
# Autenticación SSH
MSG_SSH_CHECK="🔐 Verificando configuración SSH..."
MSG_SSH_OK="✅ Conexión SSH funcionando correctamente"
MSG_SSH_FAIL="❌ No se detectó configuración SSH válida"
MSG_SSH_HELP="💡 Configura SSH ejecutando: ssh-keygen -t ed25519 -C \"tu@email.com\""
MSG_SSH_ADD_KEY="📌 Luego agrega la clave a GitHub: https://github.com/settings/ssh/new"
MSG_TOKEN_FALLBACK="🔑 Usando token como alternativa..."
MSG_TOKEN_PROMPT="📝 Ingresa tu GitHub Personal Access Token (classic o fine-grained):"
MSG_TOKEN_SAVED="✅ Token guardado en variable de entorno GITHUB_TOKEN"
MSG_AUTH_SUCCESS="✅ Autenticación configurada correctamente"
# Módulo 1 - Crear repositorio
MSG_CREATE_REPO_TITLE="${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
MSG_CREATE_REPO_HEADER="🚀 CREAR NUEVO REPOSITORIO"
MSG_REPO_NAME="📝 Nombre del repositorio:"
MSG_REPO_DESC="📄 Descripción (opcional):"
MSG_REPO_PRIVATE="🔒 ¿Repositorio privado? (s/n):"
MSG_REPO_CREATED="✅ Repositorio creado exitosamente"
MSG_REPO_EXISTS="❌ El repositorio ya existe"
MSG_REPO_CREATE_FAIL="❌ Error al crear el repositorio"
MSG_REPO_URL="🔗 URL del repositorio:"
MSG_REPO_INIT_LOCAL="📦 Inicializando repositorio local..."
MSG_REPO_ADD_REMOTE="🌐 Agregando remote origin..."
MSG_REPO_PUSH_FIRST="📤 Realizando primer push..."
# Módulo 2 - Inicializar en proyecto existente
MSG_INIT_REPO_TITLE="${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
MSG_INIT_REPO_HEADER="📁 INICIALIZAR REPOSITORIO EN PROYECTO EXISTENTE"
MSG_INIT_REPO_PATH="📂 Ruta del proyecto (actual: $(pwd)):"
MSG_INIT_GIT="🔧 Inicializando repositorio Git..."
MSG_INIT_FIRST_COMMIT="💾 Realizando primer commit..."
MSG_INIT_SUCCESS="✅ Repositorio inicializado exitosamente"
MSG_NOT_GIT_REPO="⚠️  Este directorio no es un repositorio Git"
MSG_REPO_ALREADY_INIT="ℹ️  El repositorio ya está inicializado"
# Módulo 3 - Subir cambios (nuevos mensajes)
MSG_PUSH_TITLE="${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
MSG_PUSH_HEADER="📤 SUBIR CAMBIOS A GITHUB"
MSG_PUSH_NO_CHANGES="⚠️  No hay cambios para subir"
MSG_PUSH_SUCCESS="✅ Cambios subidos exitosamente"
MSG_PUSH_ERROR="❌ Error al subir cambios"
# Módulo 5 - Estado del repositorio (nuevos mensajes)
MSG_STATUS_TITLE="${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
MSG_STATUS_HEADER="📊 ESTADO DEL REPOSITORIO"
MSG_STATUS_NO_REPO="❌ No estás en un repositorio Git"
MSG_STATUS_BRANCH="🌿 Branch actual:"
MSG_STATUS_COMMITS="📊 Total commits:"
MSG_STATUS_FILES="📁 Total archivos:"
MSG_STATUS_REMOTE="🔗 REMOTO (ORIGIN)"
MSG_STATUS_LAST_COMMIT="📝 ÚLTIMO COMMIT"
MSG_STATUS_FILE_STATS="📊 ESTADO DE ARCHIVOS"
MSG_STATUS_STAGED="✅ Staged:"
MSG_STATUS_MODIFIED="⚠️  Modified:"
MSG_STATUS_UNTRACKED="🆕 Untracked:"
MSG_STATUS_SUGGESTIONS="💡 SUGERENCIAS"
# Módulo 11 - Historial de commits (nuevos mensajes)
MSG_HISTORY_TITLE="${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
MSG_HISTORY_HEADER="📜 HISTORIAL DE COMMITS"
MSG_HISTORY_NO_COMMITS="⚠️  No hay commits en este repositorio"
MSG_HISTORY_TOTAL="📊 Resumen:"
MSG_HISTORY_FORMAT_SELECT="📋 SELECCIONA EL FORMATO DE VISUALIZACIÓN"
MSG_HISTORY_FORMAT_FULL="1) Formato completo (hash, fecha, autor, mensaje)"
MSG_HISTORY_FORMAT_ONELINE="2) Formato one-line (hash + mensaje)"
MSG_HISTORY_FORMAT_STATS="3) Con estadísticas de archivos"
MSG_HISTORY_FORMAT_GRAPH="4) Gráfico de ramas"
MSG_HISTORY_FORMAT_CONTRIB="5) Estadísticas de contribución"
MSG_HISTORY_FORMAT_SEARCH="6) Buscar commits"
MSG_HISTORY_FORMAT_COUNT="7) Cambiar cantidad de commits"
MSG_HISTORY_BACK="8) Volver al menú principal"
MSG_HISTORY_SEARCH_PROMPT="🔍 Patrón de búsqueda:"
# Mensajes de validación
MSG_VALIDATE_NAME="❌ El nombre del repositorio no puede estar vacío"
MSG_VALIDATE_NAME_INVALID="❌ Nombre inválido. Use solo letras, números, guiones y guiones bajos"
MSG_VALIDATE_YES_NO="❌ Por favor responda 's' (sí) o 'n' (no)"
